-- =====================================================================
-- RIYANALUXE — Seed placeholder
-- Product & bundle catalogue is provisioned in 008_riyana_magreb_catalog.sql.
-- Legacy pet-product SKUs are not seeded on fresh databases.
-- =====================================================================
